# Generated by Django 4.0.6 on 2022-08-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_accountant_user_is_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Range1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Range2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('End_Date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pay1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_frequency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Period_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('parish', models.CharField(max_length=200)),
                ('country', models.CharField(default='Jamaica', max_length=200)),
                ('Tax_Registration_No', models.CharField(max_length=200)),
                ('National_Insurance_Scheme_Number', models.CharField(max_length=200)),
                ('Business_Start_Date', models.DateTimeField()),
                ('Name_On_Account', models.CharField(max_length=200)),
                ('Bank_Name', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Account_Number', models.CharField(max_length=200)),
                ('Account_Type', models.CharField(max_length=200)),
                ('Date1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.data_range1')),
                ('Date2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.data_range2')),
                ('Period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.period_number')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pay1')),
            ],
        ),
    ]
